export const COMMON_REDUCER_PUBLISHER = {
  SET_PUBLISHER_ID: "SET_PUBLISHER_ID",
  SET_PUBLISHER_ID_SUCCESS: "SET_PUBLISHER_ID_SUCCESS",
};

export const COMMON_PUBLISHER_LIST_API_CALL = {
  GET_REQUEST: "COMMON_PUBLISHER_LIST_REQUEST",
  GET_SUCCESS: "COMMON_PUBLISHER_LIST_SUCCESS",
  GET_FAILURE: "COMMON_PUBLISHER_LIST_FAILURE",
};

export const COMMON_REDUCER = {
  CLEAR_REDUCER: "COMMON_CLEAR_REDUCER",
};
