export const PAGE_TEMPLATE_API_GET_CALL = {
    GET_REQUEST: "PAGE_TEMPLATE_REQUEST",
    GET_SUCCESS: "PAGE_TEMPLATE_SUCCESS",
    GET_FAILURE: "PAGE_TEMPLATE_FAILURE",
  };
  
  export const PAGE_TEMPLATE_REDUCER = {
    CLEAR_REDUCER: "PAGE_TEMPLATE_CLEAR_REDUCER",
  };
  