export const LIST_TEMPLATE_API_GET_CALL = {
  GET_REQUEST: "LIST_TEMPLATE_REQUEST",
  GET_SUCCESS: "LIST_TEMPLATE_SUCCESS",
  GET_FAILURE: "LIST_TEMPLATE_FAILURE",
};

export const LIST_TEMPLATE_REDUCER = {
  CLEAR_REDUCER: "LIST_TEMPLATE_CLEAR_REDUCER",
};
